// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkq9lYyS3LvpgTkZqVa0YH1dZcIWCfKWg',
    appId: '1:374759736062:web:b0cfb5bfbacd975e7c9baf',
    messagingSenderId: '374759736062',
    projectId: 'mediapp-c6cde',
    authDomain: 'mediapp-c6cde.firebaseapp.com',
    storageBucket: 'mediapp-c6cde.firebasestorage.app',
    measurementId: 'G-D955KZ8MBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkirUuoOKSUrlNn6GT3UzKDHhuXp_z3Xw',
    appId: '1:374759736062:android:c125d2ba8777352f7c9baf',
    messagingSenderId: '374759736062',
    projectId: 'mediapp-c6cde',
    storageBucket: 'mediapp-c6cde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCier3QTdDvis4i5fO909a64Go-1T--N74',
    appId: '1:374759736062:ios:c7011261fe64d4667c9baf',
    messagingSenderId: '374759736062',
    projectId: 'mediapp-c6cde',
    storageBucket: 'mediapp-c6cde.firebasestorage.app',
    iosBundleId: 'com.shin.media.mediapp',
  );
}
